import type { ModuleData } from "@/types/module";

// 模拟数据 - 优化后的模块数据，确保所有功能名称字数一致（四个字）
export const mockModules: ModuleData[] = [
  {
    id: "01",
    title: "数字人像",
    titleEn: "Digital Avatar",
    description: "一键克隆形象与声音，轻松生成多场景视频",
    descriptionEn:
      "Clone your image and voice with one click, easily generate videos for multiple scenarios",
    features: [
      "形象克隆",
      "音色复制",
      "音频合成",
      "视频生成",
      "文案创作",
      "批量制作",
      "静态数人",
      "直播数人",
    ],
    featuresEn: [
      "Image Clone",
      "Voice Copy",
      "Audio Synthesis",
      "Video Generation",
      "Content Creation",
      "Batch Production",
      "Static Avatar",
      "Live Avatar",
    ],
    icon: "👤",
    isFavorite: false,
    rating: 4.5,
    userRating: 0,
  },
  {
    id: "02",
    title: "智能对话",
    titleEn: "Smart Chat",
    description: "思路对接，就像跟真实文件对话",
    descriptionEn: "Connect ideas, chat with files as if they were real people",
    features: [
      "深度推理",
      "知识对话",
      "对话分享",
      "文件解析",
      "联网搜索",
      "场景对话",
      "对话导出",
      "语义理解",
    ],
    featuresEn: [
      "Deep Reasoning",
      "Knowledge Chat",
      "Chat Sharing",
      "File Analysis",
      "Web Search",
      "Scenario Chat",
      "Chat Export",
      "Semantic Understanding",
    ],
    icon: "💬",
    isFavorite: true,
    rating: 4.8,
    userRating: 5,
  },
  {
    id: "03",
    title: "微信助手",
    titleEn: "WeChat Helper",
    description: "一站式提高微信号管理，AI自动聊天与SOP模拟化客服",
    descriptionEn:
      "One-stop WeChat account management, AI auto-chat and SOP simulated customer service",
    features: [
      "账号管理",
      "智能聊天",
      "关键回复",
      "用户画像",
      "欢迎设置",
      "知识对话",
      "客户跟进",
      "朋友营销",
    ],
    featuresEn: [
      "Account Management",
      "Smart Chat",
      "Key Replies",
      "User Profiling",
      "Welcome Setup",
      "Knowledge Chat",
      "Customer Follow-up",
      "Friend Marketing",
    ],
    icon: "📱",
    isFavorite: false,
    rating: 4.2,
    userRating: 0,
  },
  {
    id: "04",
    title: "内容创作",
    titleEn: "Content Creation",
    description: "AI赋能创作，快速生成高质量文章、视频脚本",
    descriptionEn: "AI-powered creation, quickly generate high-quality articles and video scripts",
    features: [
      "文章生成",
      "脚本创作",
      "文案优化",
      "多语言翻译",
      "排版美化",
      "风格转换",
      "标题生成",
      "摘要提取",
    ],
    featuresEn: [
      "Article Generation",
      "Script Creation",
      "Copy Optimization",
      "Multilingual Translation",
      "Format Beautification",
      "Style Conversion",
      "Title Generation",
      "Summary Extraction",
    ],
    icon: "✍️",
    isFavorite: false,
    rating: 4.3,
    userRating: 0,
  },
  {
    id: "05",
    title: "图像生成",
    titleEn: "Image Generation",
    description: "文字描述变图像，AI绘画让创意瞬间实现",
    descriptionEn: "Text to image, AI painting makes creativity come true instantly",
    features: [
      "文生图像",
      "图像编辑",
      "风格迁移",
      "超分辨率",
      "背景虚化",
      "智能抠图",
      "滤镜特效",
      "批量生成",
    ],
    featuresEn: [
      "Text to Image",
      "Image Editing",
      "Style Transfer",
      "Super Resolution",
      "Background Blur",
      "AI Cutout",
      "Filter Effects",
      "Batch Generation",
    ],
    icon: "🎨",
    isFavorite: true,
    rating: 4.7,
    userRating: 5,
  },
  {
    id: "06",
    title: "语音识别",
    titleEn: "Speech Recognition",
    description: "精准识别语音，快速转录为文字，支持多语言",
    descriptionEn: "Accurately recognize speech, quickly transcribe to text, support multiple languages",
    features: [
      "语音转写",
      "实时字幕",
      "多音识别",
      "语速控制",
      "背景降噪",
      "情感分析",
      "关键词提取",
      "批量处理",
    ],
    featuresEn: [
      "Speech Transcription",
      "Real-time Subtitles",
      "Multi-speaker Recognition",
      "Speed Control",
      "Background Noise Reduction",
      "Sentiment Analysis",
      "Keyword Extraction",
      "Batch Processing",
    ],
    icon: "🎤",
    isFavorite: false,
    rating: 4.4,
    userRating: 0,
  },
  {
    id: "07",
    title: "代码助手",
    titleEn: "Code Assistant",
    description: "智能辅助编程，代码生成、调试与优化一键搞定",
    descriptionEn: "Intelligent programming assistance, code generation, debugging and optimization in one click",
    features: [
      "代码生成",
      "错误修复",
      "性能优化",
      "注释生成",
      "重构建议",
      "代码解释",
      "技术文档",
      "库依赖分析",
    ],
    featuresEn: [
      "Code Generation",
      "Error Fixing",
      "Performance Optimization",
      "Comment Generation",
      "Refactoring Suggestions",
      "Code Explanation",
      "Technical Documentation",
      "Library Dependency Analysis",
    ],
    icon: "💻",
    isFavorite: true,
    rating: 4.9,
    userRating: 5,
  },
  {
    id: "08",
    title: "数据分析",
    titleEn: "Data Analysis",
    description: "大数据分析，智能洞察业务趋势，辅助决策",
    descriptionEn: "Big data analysis, intelligent insight into business trends, decision support",
    features: [
      "数据清洗",
      "统计分析",
      "可视化图表",
      "预测模型",
      "异常检测",
      "趋势分析",
      "相关性分析",
      "报告生成",
    ],
    featuresEn: [
      "Data Cleaning",
      "Statistical Analysis",
      "Visual Charts",
      "Prediction Models",
      "Anomaly Detection",
      "Trend Analysis",
      "Correlation Analysis",
      "Report Generation",
    ],
    icon: "📊",
    isFavorite: false,
    rating: 4.6,
    userRating: 0,
  },
  {
    id: "09",
    title: "学习助手",
    titleEn: "Study Assistant",
    description: "个性化学习方案，智能辅导提升学习效率",
    descriptionEn: "Personalized learning plans, intelligent tutoring to improve learning efficiency",
    features: [
      "知识梳理",
      "题目解析",
      "学习规划",
      "记忆辅助",
      "答疑解惑",
      "知识点检测",
      "笔记生成",
      "学习报告",
    ],
    featuresEn: [
      "Knowledge Organization",
      "Problem Analysis",
      "Study Planning",
      "Memory Assistance",
      "Q&A Support",
      "Knowledge Point Detection",
      "Note Generation",
      "Study Reports",
    ],
    icon: "📚",
    isFavorite: false,
    rating: 4.5,
    userRating: 0,
  },
  {
    id: "10",
    title: "营销助手",
    titleEn: "Marketing Assistant",
    description: "AI驱动营销，创意策划与内容分发一站式解决",
    descriptionEn: "AI-driven marketing, one-stop solution for creative planning and content distribution",
    features: [
      "营销策划",
      "文案创作",
      "海报设计",
      "社媒发布",
      "效果分析",
      "竞品分析",
      "客户画像",
      "策略优化",
    ],
    featuresEn: [
      "Marketing Planning",
      "Copywriting",
      "Poster Design",
      "Social Media Publishing",
      "Performance Analysis",
      "Competitor Analysis",
      "Customer Profiling",
      "Strategy Optimization",
    ],
    icon: "📈",
    isFavorite: true,
    rating: 4.3,
    userRating: 4,
  },
  {
    id: "11",
    title: "智能翻译",
    titleEn: "Intelligent Translation",
    description: "多语言精准翻译，保留原文风格，支持专业术语",
    descriptionEn: "Multi-language precise translation, preserving original style, supporting professional terminology",
    features: [
      "文档翻译",
      "实时翻译",
      "语音翻译",
      "图片翻译",
      "术语库",
      "风格调整",
      "批量翻译",
      "翻译记忆",
    ],
    featuresEn: [
      "Document Translation",
      "Real-time Translation",
      "Speech Translation",
      "Image Translation",
      "Terminology Library",
      "Style Adjustment",
      "Batch Translation",
      "Translation Memory",
    ],
    icon: "🌐",
    isFavorite: false,
    rating: 4.6,
    userRating: 0,
  },
  {
    id: "12",
    title: "健康助手",
    titleEn: "Health Assistant",
    description: "智能健康管理，个性化建议，生活方式优化",
    descriptionEn: "Intelligent health management, personalized recommendations, lifestyle optimization",
    features: [
      "健康监测",
      "饮食建议",
      "运动规划",
      "睡眠分析",
      "压力管理",
      "健康提醒",
      "数据追踪",
      "报告生成",
    ],
    featuresEn: [
      "Health Monitoring",
      "Dietary Advice",
      "Exercise Planning",
      "Sleep Analysis",
      "Stress Management",
      "Health Reminders",
      "Data Tracking",
      "Report Generation",
    ],
    icon: "🏥",
    isFavorite: false,
    rating: 4.4,
    userRating: 0,
  }
];
